### ISSUE TITLE
MACOS下配置没有办法导出。

### ISSUE THREAD

**Issue by rongpengli** [sakuyaa/myNewTabWE#1]
系统配置：MACOS High Sierra
浏览器：Firefox 57.0.4

**Comment by sakuyaa** [comment]
我这边没有Mac OS可以调试呢
能具体说是怎样的吗，比如控制台有输出什么吗？

**Comment by rongpengli** [comment]
点击导出页面就白了，没有任何反应。另一台win10电脑就没问题。

控制台怎么看？

**Comment by sakuyaa** [comment]
按F12出来的窗口中左上角第二（三）项就是控制台了，或者按Ctrl+Shift+K

**Comment by rongpengli** [comment]
看了一下，没有任何输出

**Comment by sakuyaa** [comment]
看看1.2.1版本能不能解决吧。。。

**Comment by rongpengli** [comment]
已经解决，感谢🙏
