### ISSUE TITLE
有两个bug反馈一下

### ISSUE THREAD

**Issue by aunsen** [sakuyaa/myNewTabWE#2]
测试平台为win10，FF60-64位

1.每次打开新的标签，都要重新下载必应壁纸，能不能读取缓存？

2.再当前mynetab页面搜索跳转到搜索结果再返回mynetab时，mynetab页面一片空白，地址栏显示的是搜索地址

**Comment by aunsen** [comment]
另外在地址栏输入网站打开后再返回mynetab页面也是一片空白，地址栏里还留着输入的网址

**Comment by rongpengli** [comment]
第一个问题，我也存在。MAC OS， FF59 64位。

**Comment by sakuyaa** [comment]
1.缓存的问题由于目前WebExtension的限制无法读取本地文件，我考虑后面用localStorage来替代存储
2.会不会是使用了“New Tab from Location Bar”这个扩展呢？如果是的话请在扩展选项Blocking method中设置为webNavigation就好了

**Comment by aunsen** [comment]
我也是刚发现了这个问题New Tab from Location Bar设置为webNavigation和实用UC脚本的新标签打开功能一样都会导致mynetab重新加载一次，但是界面显示正常，不知道这个重新加载的bug是New Tab from Location Bar这个扩展的功能还是火狐本身api不够完善导致，感谢回复！

**Comment by sakuyaa** [comment]
UC脚本我用的是下面的语句，这个好像不会出现重新加载的问题
`eval('gURLBar.handleCommand=' + gURLBar.handleCommand.toString().replace(/let where = openUILinkWhere;/, "let where = 'tab';"));`

**Comment by aunsen** [comment]
下一版能不能去掉天气预报，有时候链接速度很慢导致mynetab一直转圈，还有就是定制的css还是会后于内置默认的css后加载，设置了上下距离后很明显

**Comment by sakuyaa** [comment]
天气预报只要URL留空就不会显示了
css我记得定制的和默认的都在同个函数initCss()里面判断加载。网页打开后需要先读取配置，这个函数已经放在读取配置后最前面进行加载了

**Comment by aunsen** [comment]
下一版能不能去掉天气预报，有时候链接速度很慢导致mynetab一直转圈，还有就是定制的css还是会后于内置默认的css后加载，设置了上下距离后很明显

**Comment by aunsen** [comment]
应该是我隐藏了农历日期后导致的网址框一个下沉的动画效果，最好是改成白色文字放到‘我的导航’这一行后最好，现在的默认很丑啊，别打我。。。

**Comment by rongpengli** [comment]
缓存的问题解决了吗？

**Comment by sakuyaa** [comment]
新版本已经有缓存壁纸了
