### ISSUE TITLE
能做一个老版配置转换的本地页么，自定义网址一个一个的增加真的很麻烦啊

### ISSUE THREAD

**Issue by ghost** [sakuyaa/myNewTabWE#3]
非we的版本自定义的网址有近100个，这要是一个一个的增加，太繁琐了。看了下we版导出的json结构，能不能出个工具把旧版的data.txt和ico文件夹内*.ico、jpg、svg自动转换为json和base64格式的？

**Comment by sakuyaa** [comment]
主要是WE不能读取本地文件，我当时也是一个一个加进去的，不过还好这是一次性工作，加完就不用怎么改了

**Comment by ghost** [comment]
我的意思是做个bat  或者其他的什么工具，放在老版的文件夹李自动转换，100多个实在手抽筋

**Comment by sakuyaa** [comment]
不好意思能力实在有限啊，当初我那个快200个的配置也是手工一个一个加进去的。。。
