### ISSUE TITLE
希望给每个分组间加上一条分隔线，这样分组之间看起来会比较清晰。

### ISSUE THREAD

**Issue by CraftX2025** [sakuyaa/myNewTabWE#4]
希望给每个分组间加上一条分隔线，这样分组之间看起来会比较清晰。
还有一个，网址可否跨分组移动？现在我多个网址就导出编辑再导入的。

![default](https://user-images.githubusercontent.com/39214887/40278715-d8885c02-5c68-11e8-8f84-bc14a769df87.png)

**Comment by sakuyaa** [comment]
分隔线可以在定制页面里，在默认的定制主页css里，中间的代码换成下面的，也可以自行修改代码

> /*导航表格*/
#navtable {
	padding: .25em 1em;
	border-collapse: collapse;
}
#navtable tr {
	border-bottom: 1px rgba(255, 255, 255, .3) solid;
}
/*设置导航分类*/
#navtable th {
	color: rgba(255, 255, 255, .6);
	padding: .3em .9em;
	text-align: left;
	width: 6em;
}

网址现在不能跨分组移动的，感觉能跨分组移动这功能实现起来逻辑什么的有些麻烦。。。

**Comment by salut66** [comment]
10.152.209.79

**Comment by CraftX2025** [comment]
谢谢你的回复，我加入下面的代码：
#navtable tr {
border-bottom: 1px rgba(255, 255, 255, .3) solid;
}
刷新后没有什么变化。
又在虚拟机的浏览器里面新安装了这个扩展，也是只加上面的代码，同样没有效果。
用火狐的web开发者查看器，能显示这行代码，就是不起作用。

**Comment by sakuyaa** [comment]
导航表格也得相应更改的
> #navtable {
padding: .25em 1em;
border-collapse: collapse;
}

**Comment by CraftX2025** [comment]
成功了:-)   看起来更直观了。
非常感谢你的支持！
