### ISSUE TITLE
配置文件路径

### ISSUE THREAD

**Issue by Loofer** [sakuyaa/myNewTabWE#6]
请问配置文件放在哪个目录，我想用 git 做版本控制，谢谢。

**Comment by sakuyaa** [comment]
在火狐里是浏览器管理的，在配置文件夹里的`browser-extension-data\myNewTabWE@sakuyaa\storage.js`这个文件

**Comment by Loofer** [comment]
感谢，看到了，再问一句能在扩展中自定义去调用该目录下的 bat 脚本吗，我想用 git 备份配置，想修改扩展加个按钮调用该目录下的 bat push 到 github 来备份

**Comment by sakuyaa** [comment]
WebExtension不支持调用本地文件呢，可以考虑用系统的任务计划程序来定时执行bat

**Comment by Loofer** [comment]
感谢！，了解
